/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Tile counts, the three "needs attention" lists and the next interviews.
         *
         *     Days are whole calendar days in your time zone; only status changes count as
         *     movement. The thresholds used are returned too, for the UI's wording.
         */
        get: operations["get_dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Interview Groups
         * @description All your interviews in three groups.
         *
         *     - **upcoming**: from now on, soonest first (including closed jobs, so a booking you
         *       no longer need stays visible);
         *     - **not_yet_scheduled**: no date yet, on active jobs only, oldest first;
         *     - **past**: most recent first.
         */
        get: operations["interview_groups_api_interviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Jobs matching the filter (a status, `active` or `all`) and search, one page at a time.
         *
         *     `q` searches company and role (case-insensitive, at least 2 characters). `counts`
         *     gives every status's total across all your jobs, ignoring the filter and search.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /**
         * Create Job
         * @description Create a job. 409 with the existing job's id if you already track this URL.
         */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Change Status
         * @description Set many jobs' status at once (e.g. "Mark all as no response"), all or nothing.
         *
         *     Only your own jobs are changed: any other ID is reported in `not_found` and never
         *     touched. Jobs already in the status are reported in `unchanged`.
         */
        post: operations["bulk_change_status_api_jobs_bulk_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/company-matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Company Matches
         * @description Your jobs at companies whose name matches, by the start of a word.
         *
         *     Case, punctuation and legal suffixes (Ltd, Limited, Inc…) are ignored when matching,
         *     so "acme" finds "ACME" and "Acme Ltd", and "ac" also finds "Accenture" (but not
         *     "Pacific"). Each name is returned as entered, with its own counts: nothing is merged.
         */
        get: operations["company_matches_api_jobs_company_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a job permanently, with its status history and interviews.
         */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Job
         * @description Change only the fields sent; null clears an optional field. Not the status (JT-26).
         */
        patch: operations["update_job_api_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status History
         * @description The job's status changes, newest first.
         */
        get: operations["status_history_api_jobs__job_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Job Interviews
         * @description A job's interviews: scheduled ones by date, then unscheduled ones.
         */
        get: operations["list_job_interviews_api_jobs__job_id__interviews_get"];
        put?: never;
        /**
         * Create Interview
         * @description Add an interview. Every field is optional; the job's status doesn't change.
         */
        post: operations["create_interview_api_jobs__job_id__interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/interviews/{interview_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_api_jobs__job_id__interviews__interview_id__get"];
        put?: never;
        post?: never;
        /** Delete Interview */
        delete: operations["delete_interview_api_jobs__job_id__interviews__interview_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Interview
         * @description Change only the fields sent; null clears a field.
         */
        patch: operations["update_interview_api_jobs__job_id__interviews__interview_id__patch"];
        trace?: never;
    };
    "/api/jobs/{job_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Status
         * @description Change a job's status, recording it in the history.
         *
         *     Any status can move to any other. Setting the status it already has changes nothing.
         *     Becoming `applied` fills in today's date (in your time zone) if there's none;
         *     going back to `saved` clears it.
         */
        post: operations["change_status_api_jobs__job_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/timezone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Timezone
         * @description Store your IANA time zone (e.g. Europe/London), used for server-side dates.
         */
        put: operations["set_timezone_api_me_timezone_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BulkStatusChange */
        BulkStatusChange: {
            /** Ids */
            ids: string[];
            status: components["schemas"]["JobStatus"];
        };
        /** BulkStatusResult */
        BulkStatusResult: {
            /** Not Found */
            not_found: string[];
            /** Unchanged */
            unchanged: string[];
            /** Updated */
            updated: string[];
        };
        /** CompanyMatch */
        CompanyMatch: {
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Name */
            name: string;
            /** Total */
            total: number;
        };
        /** CompanyMatches */
        CompanyMatches: {
            /** Companies */
            companies: components["schemas"]["CompanyMatch"][];
        };
        /** DashboardCounts */
        DashboardCounts: {
            /** Accepted */
            accepted: number;
            /** Active */
            active: number;
            /** Applied Ever */
            applied_ever: number;
            /** Interviewing */
            interviewing: number;
            /** No Response */
            no_response: number;
            /** Offer */
            offer: number;
            /** Rejected After Interview */
            rejected_after_interview: number;
            /** Rejected At Application */
            rejected_at_application: number;
            /** Saved */
            saved: number;
            /** Withdrawn */
            withdrawn: number;
        };
        /** DashboardOut */
        DashboardOut: {
            counts: components["schemas"]["DashboardCounts"];
            /** Needs Follow Up */
            needs_follow_up: components["schemas"]["StaleJobOut"][];
            /** No Response Candidates */
            no_response_candidates: components["schemas"]["StaleJobOut"][];
            /** Still To Apply */
            still_to_apply: components["schemas"]["StaleJobOut"][];
            thresholds: components["schemas"]["DashboardThresholds"];
            /** Upcoming Interviews */
            upcoming_interviews: components["schemas"]["InterviewWithJob"][];
            /** Upcoming Interviews Total */
            upcoming_interviews_total: number;
        };
        /** DashboardThresholds */
        DashboardThresholds: {
            /** No Response After Days */
            no_response_after_days: number;
            /** Stale After Days */
            stale_after_days: number;
        };
        /** DuplicateJob */
        DuplicateJob: {
            /**
             * Detail
             * @default Already tracked
             */
            detail: string;
            /**
             * Existing Id
             * Format: uuid
             */
            existing_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntry */
        HistoryEntry: {
            /**
             * Changed At
             * Format: date-time
             */
            changed_at: string;
            status: components["schemas"]["JobStatus"];
        };
        /** InterviewCreate */
        InterviewCreate: {
            mode?: components["schemas"]["InterviewMode"] | null;
            /** Notes */
            notes?: string | null;
            /** Round Label */
            round_label?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
        /** InterviewGroups */
        InterviewGroups: {
            /** Not Yet Scheduled */
            not_yet_scheduled: components["schemas"]["InterviewWithJob"][];
            /** Past */
            past: components["schemas"]["InterviewWithJob"][];
            /** Upcoming */
            upcoming: components["schemas"]["InterviewWithJob"][];
        };
        /**
         * InterviewMode
         * @enum {string}
         */
        InterviewMode: "remote" | "in_person" | "phone";
        /** InterviewOut */
        InterviewOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            mode: components["schemas"]["InterviewMode"] | null;
            /** Notes */
            notes: string | null;
            /** Round Label */
            round_label: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
        };
        /**
         * InterviewUpdate
         * @description A partial update: only the fields sent change, and null clears a field.
         */
        InterviewUpdate: {
            mode?: components["schemas"]["InterviewMode"] | null;
            /** Notes */
            notes?: string | null;
            /** Round Label */
            round_label?: string | null;
            /** Scheduled At */
            scheduled_at?: string | null;
        };
        /** InterviewWithJob */
        InterviewWithJob: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobSummary"];
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            mode: components["schemas"]["InterviewMode"] | null;
            /** Notes */
            notes: string | null;
            /** Round Label */
            round_label: string | null;
            /** Scheduled At */
            scheduled_at: string | null;
        };
        /** JobCreate */
        JobCreate: {
            /** Applied At */
            applied_at?: string | null;
            /** Company */
            company: string;
            /** Contact Email */
            contact_email?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Location */
            location?: string | null;
            /** Notes */
            notes?: string | null;
            /** Role */
            role: string;
            /** Salary */
            salary?: string | null;
            source?: components["schemas"]["JobSource"] | null;
            /** @default saved */
            status: components["schemas"]["JobStatus"];
            /** Url */
            url?: string | null;
        };
        /** JobOut */
        JobOut: {
            /** Applied At */
            applied_at: string | null;
            /** Attention */
            attention: ("needs_follow_up" | "still_to_apply" | "no_response") | null;
            /** Company */
            company: string;
            /** Contact Email */
            contact_email: string | null;
            /** Contact Name */
            contact_name: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days Since Last Change */
            days_since_last_change: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Status Change At
             * Format: date-time
             */
            last_status_change_at: string;
            /** Location */
            location: string | null;
            /** Notes */
            notes: string | null;
            /** Role */
            role: string;
            /** Salary */
            salary: string | null;
            source: components["schemas"]["JobSource"] | null;
            status: components["schemas"]["JobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url: string | null;
        };
        /** JobPage */
        JobPage: {
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["JobOut"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /**
         * JobSource
         * @enum {string}
         */
        JobSource: "linkedin" | "company_site" | "referral" | "recruiter" | "indeed" | "other";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "saved" | "applied" | "interviewing" | "offer" | "accepted" | "rejected" | "withdrawn" | "no_response";
        /** JobSummary */
        JobSummary: {
            /** Company */
            company: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobUpdate
         * @description A partial update: only the fields sent change, and null clears an optional field.
         *
         *     Status changes aren't made here (JT-26), so `status` is rejected as an unknown field.
         */
        JobUpdate: {
            /** Applied At */
            applied_at?: string | null;
            /** Company */
            company?: string | null;
            /** Contact Email */
            contact_email?: string | null;
            /** Contact Name */
            contact_name?: string | null;
            /** Location */
            location?: string | null;
            /** Notes */
            notes?: string | null;
            /** Role */
            role?: string | null;
            /** Salary */
            salary?: string | null;
            source?: components["schemas"]["JobSource"] | null;
            /** Url */
            url?: string | null;
        };
        /** Me */
        Me: {
            /** Email */
            email: string;
            /** Timezone */
            timezone: string;
        };
        /** StaleJobOut */
        StaleJobOut: {
            /** Company */
            company: string;
            /** Days Since Last Change */
            days_since_last_change: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Status Change At
             * Format: date-time
             */
            last_status_change_at: string;
            /** Role */
            role: string;
            status: components["schemas"]["JobStatus"];
        };
        /** StatusChange */
        StatusChange: {
            status: components["schemas"]["JobStatus"];
        };
        /** TimezoneOut */
        TimezoneOut: {
            /** Timezone */
            timezone: string;
        };
        /** TimezoneUpdate */
        TimezoneUpdate: {
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    interview_groups_api_interviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewGroups"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: ("active" | "all") | components["schemas"]["JobStatus"];
                q?: string | null;
                sort?: "company" | "role" | "status" | "last_status_change" | "applied_at" | "created_at";
                order?: "asc" | "desc";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_change_status_api_jobs_bulk_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkStatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    company_matches_api_jobs_company_matches_get: {
        parameters: {
            query: {
                company: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyMatches"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_api_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_history_api_jobs__job_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_interviews_api_jobs__job_id__interviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_api_jobs__job_id__interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_api_jobs__job_id__interviews__interview_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_interview_api_jobs__job_id__interviews__interview_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_interview_api_jobs__job_id__interviews__interview_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                interview_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_jobs__job_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    set_timezone_api_me_timezone_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimezoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimezoneOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
