# Copyright (C) 2026 Luke Brewerton
# SPDX-License-Identifier: AGPL-3.0-or-later
"""initial schema

Creates users, sessions, jobs, status_history and interviews, and puts row-level
security on the three data tables (jobs, status_history, interviews).

Revision ID: e3521fb119d8
Revises:
Create Date: 2026-09-23 17:54:32.595612

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# Tables whose rows belong to a user and are isolated by row-level security. `users` and
# `sessions` are deliberately excluded: they are read to establish who the user is,
# before any `app.user_id` exists, and only the auth code touches them.
RLS_TABLES = ("jobs", "status_history", "interviews")

# Matches only the current transaction's user (set with set_config(..., true)). With no
# user set, nullif() turns '' into NULL and the comparison matches nothing: fail closed.
_OWNED_BY_CURRENT_USER = "user_id = nullif(current_setting('app.user_id', true), '')::uuid"

# revision identifiers, used by Alembic.
revision: str = "e3521fb119d8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("oidc_sub", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(email) <= 320", name=op.f("ck_users_email_max_len")),
        sa.CheckConstraint("char_length(oidc_sub) <= 255", name=op.f("ck_users_oidc_sub_max_len")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("oidc_sub", name=op.f("uq_users_oidc_sub")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("url_canonical", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "linkedin",
                "company_site",
                "referral",
                "recruiter",
                "indeed",
                "other",
                name="job_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("salary", sa.Text(), nullable=True),
        sa.Column("contact_name", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "applied",
                "interviewing",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                "no_response",
                name="job_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            server_default="saved",
            nullable=False,
        ),
        sa.Column("applied_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(company) <> ''", name=op.f("ck_jobs_company_not_blank")),
        sa.CheckConstraint("btrim(role) <> ''", name=op.f("ck_jobs_role_not_blank")),
        sa.CheckConstraint("char_length(company) <= 200", name=op.f("ck_jobs_company_max_len")),
        sa.CheckConstraint(
            "char_length(contact_email) <= 320", name=op.f("ck_jobs_contact_email_max_len")
        ),
        sa.CheckConstraint(
            "char_length(contact_name) <= 320", name=op.f("ck_jobs_contact_name_max_len")
        ),
        sa.CheckConstraint("char_length(location) <= 320", name=op.f("ck_jobs_location_max_len")),
        sa.CheckConstraint("char_length(notes) <= 10000", name=op.f("ck_jobs_notes_max_len")),
        sa.CheckConstraint("char_length(role) <= 200", name=op.f("ck_jobs_role_max_len")),
        sa.CheckConstraint("char_length(salary) <= 320", name=op.f("ck_jobs_salary_max_len")),
        sa.CheckConstraint("char_length(url) <= 2048", name=op.f("ck_jobs_url_max_len")),
        sa.CheckConstraint(
            "char_length(url_canonical) <= 2048", name=op.f("ck_jobs_url_canonical_max_len")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("id", "user_id", name="uq_jobs_id_user_id"),
    )
    op.create_index("ix_jobs_user_id_status", "jobs", ["user_id", "status"], unique=False)
    op.create_index(
        "uq_jobs_user_id_url_canonical",
        "jobs",
        ["user_id", "url_canonical"],
        unique=True,
        postgresql_where=sa.text("url_canonical IS NOT NULL"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "token_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_sessions_token_hash_sha256_hex")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "interviews",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "remote",
                "in_person",
                "phone",
                name="interview_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("round_label", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(notes) <= 10000", name=op.f("ck_interviews_notes_max_len")),
        sa.CheckConstraint(
            "char_length(round_label) <= 320", name=op.f("ck_interviews_round_label_max_len")
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "user_id"],
            ["jobs.id", "jobs.user_id"],
            name=op.f("fk_interviews_job_id_user_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
    )
    op.create_index(
        "ix_interviews_user_id_scheduled_at",
        "interviews",
        ["user_id", "scheduled_at"],
        unique=False,
    )
    op.create_table(
        "status_history",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "saved",
                "applied",
                "interviewing",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                "no_response",
                name="status_history_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id", "user_id"],
            ["jobs.id", "jobs.user_id"],
            name=op.f("fk_status_history_job_id_user_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_history")),
    )
    op.create_index(
        "ix_status_history_job_id_changed_at",
        "status_history",
        ["job_id", sa.literal_column("changed_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###

    # --- Row-level security (hand-written: autogenerate can't express it) ------------
    # FORCE makes the policies apply to the table owner too, which is the role the app
    # connects as. (Superusers/BYPASSRLS roles would still skip them; alembic/env.py
    # refuses to run as one.)
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY user_isolation ON {table} FOR ALL "
            f"USING ({_OWNED_BY_CURRENT_USER}) WITH CHECK ({_OWNED_BY_CURRENT_USER})"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS user_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_status_history_job_id_changed_at", table_name="status_history")
    op.drop_table("status_history")
    op.drop_index("ix_interviews_user_id_scheduled_at", table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        "uq_jobs_user_id_url_canonical",
        table_name="jobs",
        postgresql_where=sa.text("url_canonical IS NOT NULL"),
    )
    op.drop_index("ix_jobs_user_id_status", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("users")
    # ### end Alembic commands ###
