# Copyright (C) 2026 Luke Brewerton
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Database models. The design record is the "Data model" section of ARCHITECTURE.md.

- Primary keys are UUIDv7, generated by Postgres 18's `uuidv7()` so every insert path
  gets one; they can't be guessed or enumerated.
- Enums are text + CHECK constraints (not native Postgres enums): adding a value is an
  ordinary migration.
- `jobs`, `status_history` and `interviews` are protected by row-level security (see the
  migration). Children carry their own `user_id`, tied to their job's owner by a
  composite foreign key, so they can never point at another user's job.
- Deletes are hard and cascade: deleting a job removes its history and interviews.
"""

import uuid
from datetime import date, datetime
from enum import StrEnum

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base
from app.timezones import DEFAULT_TIMEZONE, TIMEZONE_MAX

# Length limits: a last line of defence. The API validates the same limits with
# friendly errors.
NAME_MAX = 200  # company, role
URL_MAX = 2048
SHORT_TEXT_MAX = 320  # location, salary, contact name/email, round label, email
NOTES_MAX = 10_000


class JobStatus(StrEnum):
    SAVED = "saved"
    APPLIED = "applied"
    INTERVIEWING = "interviewing"
    OFFER = "offer"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    WITHDRAWN = "withdrawn"
    NO_RESPONSE = "no_response"


class JobSource(StrEnum):
    LINKEDIN = "linkedin"
    COMPANY_SITE = "company_site"
    REFERRAL = "referral"
    RECRUITER = "recruiter"
    INDEED = "indeed"
    OTHER = "other"


class InterviewMode(StrEnum):
    REMOTE = "remote"
    IN_PERSON = "in_person"
    PHONE = "phone"


def _text_enum(enum: type[StrEnum], name: str) -> sa.Enum:
    """Store an enum as text with a CHECK constraint on its values."""
    return sa.Enum(
        enum,
        name=name,
        native_enum=False,
        create_constraint=True,
        length=32,
        values_callable=lambda e: [member.value for member in e],
        validate_strings=True,
    )


def _max_len(column: str, limit: int) -> sa.CheckConstraint:
    return sa.CheckConstraint(f"char_length({column}) <= {limit}", name=f"{column}_max_len")


def _not_blank(column: str) -> sa.CheckConstraint:
    return sa.CheckConstraint(f"btrim({column}) <> ''", name=f"{column}_not_blank")


def _uuid_pk() -> Mapped[uuid.UUID]:
    return mapped_column(sa.Uuid, primary_key=True, server_default=sa.text("uuidv7()"))


def _timestamp_now(*, on_update: bool = False) -> Mapped[datetime]:
    return mapped_column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        onupdate=sa.func.now() if on_update else None,
    )


class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        sa.CheckConstraint("email = lower(email)", name="email_lowercase"),
        _max_len("email", SHORT_TEXT_MAX),
        _max_len("oidc_sub", 255),
        _max_len("timezone", TIMEZONE_MAX),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    # The issuer's stable subject identifier: the identity key (email is not).
    oidc_sub: Mapped[str] = mapped_column(sa.Text, unique=True)
    email: Mapped[str] = mapped_column(sa.Text)
    # IANA zone (e.g. Europe/London) for server-side calendar dates; see app/timezones.py.
    timezone: Mapped[str] = mapped_column(sa.Text, server_default=DEFAULT_TIMEZONE)
    created_at: Mapped[datetime] = _timestamp_now()


class Session(Base):
    __tablename__ = "sessions"
    __table_args__ = (
        # SHA-256 hex digest of the cookie token; the raw token is never stored.
        sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name="token_hash_sha256_hex"),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(
        sa.ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    token_hash: Mapped[str] = mapped_column(sa.Text, unique=True)
    created_at: Mapped[datetime] = _timestamp_now()
    last_seen_at: Mapped[datetime] = _timestamp_now()


class Job(Base):
    __tablename__ = "jobs"
    __table_args__ = (
        # Target of the children's composite foreign keys.
        sa.UniqueConstraint("id", "user_id", name="uq_jobs_id_user_id"),
        # One job per canonical URL per user; jobs without a URL are unconstrained.
        sa.Index(
            "uq_jobs_user_id_url_canonical",
            "user_id",
            "url_canonical",
            unique=True,
            postgresql_where=sa.text("url_canonical IS NOT NULL"),
        ),
        sa.Index("ix_jobs_user_id_status", "user_id", "status"),
        # `saved` means "not applied yet": a saved job can't have an applied date.
        sa.CheckConstraint(
            "status <> 'saved' OR applied_at IS NULL", name="saved_has_no_applied_at"
        ),
        _not_blank("company"),
        _not_blank("role"),
        _max_len("company", NAME_MAX),
        _max_len("role", NAME_MAX),
        _max_len("url", URL_MAX),
        _max_len("url_canonical", URL_MAX),
        _max_len("location", SHORT_TEXT_MAX),
        _max_len("salary", SHORT_TEXT_MAX),
        _max_len("contact_name", SHORT_TEXT_MAX),
        _max_len("contact_email", SHORT_TEXT_MAX),
        _max_len("notes", NOTES_MAX),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    user_id: Mapped[uuid.UUID] = mapped_column(sa.ForeignKey("users.id", ondelete="CASCADE"))
    company: Mapped[str] = mapped_column(sa.Text)
    role: Mapped[str] = mapped_column(sa.Text)
    url: Mapped[str | None] = mapped_column(sa.Text)
    url_canonical: Mapped[str | None] = mapped_column(sa.Text)
    location: Mapped[str | None] = mapped_column(sa.Text)
    source: Mapped[JobSource | None] = mapped_column(_text_enum(JobSource, "job_source"))
    salary: Mapped[str | None] = mapped_column(sa.Text)
    contact_name: Mapped[str | None] = mapped_column(sa.Text)
    contact_email: Mapped[str | None] = mapped_column(sa.Text)
    status: Mapped[JobStatus] = mapped_column(
        _text_enum(JobStatus, "job_status"), server_default=JobStatus.SAVED.value
    )
    applied_at: Mapped[date | None] = mapped_column(sa.Date)
    notes: Mapped[str | None] = mapped_column(sa.Text)
    created_at: Mapped[datetime] = _timestamp_now()
    updated_at: Mapped[datetime] = _timestamp_now(on_update=True)


def _owned_by_job() -> sa.ForeignKeyConstraint:
    """Composite FK: a child row's user_id must match its job's owner."""
    return sa.ForeignKeyConstraint(
        ["job_id", "user_id"],
        ["jobs.id", "jobs.user_id"],
        ondelete="CASCADE",
    )


class StatusHistory(Base):
    __tablename__ = "status_history"
    __table_args__ = (
        _owned_by_job(),
        sa.Index("ix_status_history_job_id_changed_at", "job_id", sa.text("changed_at DESC")),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    job_id: Mapped[uuid.UUID] = mapped_column(sa.Uuid)
    # Denormalised for row-level security; the composite FK guarantees it's the job owner.
    user_id: Mapped[uuid.UUID] = mapped_column(sa.Uuid)
    status: Mapped[JobStatus] = mapped_column(_text_enum(JobStatus, "status_history_status"))
    changed_at: Mapped[datetime] = _timestamp_now()


class Interview(Base):
    __tablename__ = "interviews"
    __table_args__ = (
        _owned_by_job(),
        sa.Index("ix_interviews_user_id_scheduled_at", "user_id", "scheduled_at"),
        _max_len("round_label", SHORT_TEXT_MAX),
        _max_len("notes", NOTES_MAX),
    )

    id: Mapped[uuid.UUID] = _uuid_pk()
    job_id: Mapped[uuid.UUID] = mapped_column(sa.Uuid)
    user_id: Mapped[uuid.UUID] = mapped_column(sa.Uuid)
    # Nullable: "moved to interview stage, no date yet" is the common case.
    scheduled_at: Mapped[datetime | None] = mapped_column(sa.DateTime(timezone=True))
    # Nullable, like scheduled_at: often not known when the interview is first recorded.
    mode: Mapped[InterviewMode | None] = mapped_column(_text_enum(InterviewMode, "interview_mode"))
    round_label: Mapped[str | None] = mapped_column(sa.Text)
    notes: Mapped[str | None] = mapped_column(sa.Text)
    created_at: Mapped[datetime] = _timestamp_now()
